name: Notify on Release

on:
  release:
    types: 
      - published

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Telegram Notification
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_TO }}
      run: |
        curl -X POST https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage \
        -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
        -d text="Новый релиз: ${{ github.event.release.name }}\n${{ github.event.release.html_url }}"

