name: Notify on Releases
on:
   release:
         types: 
         - published
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Telegram Notification
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_TO }}
        TAG_NAME: ${{ github.event.release.tag_name }}
        RELEASE_DESC: ${{github.event.release.body}}
      run: |
        curl -X POST https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage \
        -d chat_id=${{ env.TELEGRAM_CHAT_ID }} \
        -d parse_mode="Markdown" \
        --data-urlencode text="
        🚀 *Asv.Drones version $TAG_NAME Release Update!*
        `We are excited to announce the release of version $TAG_NAME, packed with new features,`
        `improvements, and essential fixes to enhance your experience` 
        $RELEASE_DESC ${{ github.event.release.name }} [inline URL](${{ github.event.release.html_url }}) "
